### PR TITLE
add "how to migrate" proposal

### PR DESCRIPTION
**Pull request by btford**
I know I'm late, but here's a proposal, hope it's cool.

I also wrote up this alternate talk cuz I'm feeling indecisive: #181

:heart:

### CODE REVIEW

**Comment by danielstern** [comment]
+1

**Comment by geddski** [comment]
@btford gotta have the new router talk, but this one looks amazing too. You guys may have enough slots left for both if you're up for it. What do you think?

**Comment by btford** [comment]
I could do both. Or if someone else is looking for a topic to present on,
they can take this.

**Comment by btford** [comment]
Also I think this can fit into a smaller slot and be more of a "lightning talk."

**Comment by geddski** [comment]
@btford Igor says you're covering this material in your router talk so closing this.

**Pull request closed without merging**
