### PR TITLE
Profile picture change

### PR DESCRIPTION
**Pull request by kentcdodds**
I'm getting LASIK before the conference. So a change in profile pic is in order! Thanks!

### CODE REVIEW

**Comment by ocombe** [comment]
Hey you're looking way better without the glasses! :+1:

**Comment by kentcdodds** [comment]
Thanks @ocombe. Unfortunately I didn't get the procedure done before ng-nl so you'll see me this week with glasses still :-)

**Comment by kentcdodds** [comment]
Just in time! LASIK operation tomorrow morning! #sostoked!

**Comment by geddski** [comment]
@kentcdodds good luck man! Let me know how you like it!

**Pull request merged**
