### PR TITLE
angular-meteor  spelling and grammar fixes

### PR DESCRIPTION
**Pull request by Urigo**

### CODE REVIEW

**Comment by Urigo** [comment]
@geddski hi, sorry for all the spam, but is it possible to use those fixes in the schedule description?
Thank you so much

**Comment by geddski** [comment]
Sorry for the delay, wasn't sure how to handle the hack night preso case. Should be good now. Thanks!

**Comment by Urigo** [comment]
@geddski thank you so much!

Will it be updated in the site as well?

See you soon!

**Comment by geddski** [comment]
I'll make sure it is. 



—

**Comment by Urigo** [comment]
@geddski thank you so much

**Pull request merged**
