### PR TITLE
angular-meteor

### PR DESCRIPTION
**Pull request by Urigo**
I'm the creator of [angular-meteor](https://github.com/Urigo/angular-meteor).
More info can be found here:
[angularjs.meteor.com](http://angularjs.meteor.com/)

### CODE REVIEW

**Comment by 0a-** [comment]
+1

**Comment by drewprescott** [comment]
+1

**Comment by jonaustin** [comment]
+1

**Comment by yagoferrer** [comment]
+1 see you in ng-conf 2015!

**Comment by ajit009** [comment]
+1

**Comment by chompomonim** [comment]
+1

**Comment by deiucanta** [comment]
+1

**Comment by sclausen** [comment]
+1

**Comment by biomassives** [comment]
+1 like @prescottprue , this project helped me to launch with meteor, thank you.

**Comment by d-oliveros** [comment]
This is amazing. +1

**Comment by reneras** [comment]
Great stuff :+1:

**Comment by montoya-azul** [comment]
+1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xergioalex** [comment]
Awesome!!!

**Comment by kilatev** [comment]
:+1:

**Comment by joeeames** [comment]
Closed due to overwhelming +1 spam and because this will be a presentation at Hack Night at ng-conf!

**Comment by montoya-azul** [comment]
OH YEAH!

**Comment by Slava** [comment]
The Internet, you did again!

**Comment by danielstern** [comment]
+1

**Comment by sebakerckhof** [comment]
+1

**Comment by brugnara** [comment]
+1!

**Comment by ndevr** [comment]
+1

**Comment by Tim-W** [comment]
+1

**Comment by liuqingc** [comment]
+1

**Comment by GovardhanChaudhari** [comment]
Fantastic,  expecting jade templating instead of ugly html templates

**Comment by xanecs** [comment]
+1

**Comment by geddski** [comment]
This is going to make a great hack night preso. Glad so many people are interested. Now stop +1ing! :)

**Comment by Urigo** [comment]
@geddski thank you so much for accepting the talk!

Is there a place that the talk is published so I can go around spreading the word and and that might also help with getting less +1?

**Comment by geddski** [comment]
We'll get it on the site & schedule soon I promise!

**Comment by Urigo** [comment]
amazing!  I'm so excited

**Comment by vasya10** [comment]
+1

**Comment by brunodb3** [comment]
Looks so cool man! Congratulations, i'm really looking forward to it!! Awesome!

**Comment by plex0r** [comment]
+1

**Comment by nricca** [comment]
+1

**Comment by digioak** [comment]
+1, thank you!

**Comment by Urigo** [comment]
The great people of this amazing thread - it worked!  the great ng-conf organizers have agreed to let me talk about angular-meteor in the ng-conf:  http://www.ng-conf.org/schedule

I just want to say to each one of you - thank you so much! 
I'm overwhelmed by your support and community that gathered around angular-meteor, each day I'm getting in contact with people and I just can't describe how happy I am.

For the last month I've been in San Fransisco, talking a lot with both the Meteor and the Angular teams about insights our community get from working with both Frameworks and I can definitely say that the future is bright, all sides are learning a lot  from this collaboration - Meteor, Angular and angular-meteor. 

Next - there are a lot of sleepless nights for me working on the ng-conf slides and then - version 1.0.

logooo

**Comment by danielstern** [comment]
+:100:

**Comment by YonathanB** [comment]
really good!
I've just watch all the videos

**Comment by kennethpdev** [comment]
Great! Its really good! Awesome vid!

**Pull request closed without merging**
