### PR TITLE
submit(proposal): State of 1.x

### PR DESCRIPTION
**Pull request by naomiblack**
This is a partial -- still missing a photo and bio for Lucas.

### CODE REVIEW

**Comment by geddski** [comment]
@naomiblack thanks! Could you add a profile2.png for Lucas, and also add his twitter, email, bio etc to the proposal.yml?

**Comment by geddski** [comment]
@naomiblack ping

**Comment by lgalfaso** [comment]
@geddski sorry, it was my fault. She was waiting for a follow-up commit from me. Here it is commit/2a3732bdb341c69137f38e5e6018f7df3ae77d14

**Comment by geddski** [comment]
@lgalfaso we need a picture of you in that other PR please :)

**Pull request merged**
